[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
immolate = "2h7AsVek8XeCFPM6rJoskmM6KyLr39tQwkUFd8eb3TJM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.validator.account]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
filename = "tests/clones/usdc.json"

[[test.validator.account]]
address = "G7rwEgk8KgQ4RUTnMy2W2i7dRDq4hXHD4CSp9PSmSbRW"
filename = "tests/clones/chad.json"